### ISSUE TITLE
Fix for icon issue

### ISSUE THREAD

**Issue by mmtrt** [fefeh1/notepadqq#1]
To fix icon issue properly add this to yaml

      fixicon:
        plugin: nil
        after: [my-part]
        install: |
          sed -i 's|Icon=notepadqq|Icon=/usr/local/share/icons/hicolor/scalable/apps/notepadqq\.svg|' $SNAPCRAFT_STAGE/usr/local/share/applications/notepadqq.desktop

add remove below line from yaml and svg file from snap repo.

`icon: notepadqq.svg`

**Comment by fefeh1** [comment]
Thank you so much.  Can you try the edge version before I release it to stable?

**Comment by mmtrt** [comment]
@fefeh1 I pretty much tested above code on local build snap before posting well anyways I have tested snap from edge icon is now fixed no problem.
