### ISSUE TITLE
Official package

### ISSUE THREAD

**Issue by danieleds** [fefeh1/notepadqq#2]
Hi!
I'm the owner of the Notepadqq project. Nice work you're doing here!

We're planning to publish an official Snap package for the project, and so we will soon require the right to use the snap name "notepadqq" which is currently taken by this package.

However, as your package is already quite good, I'd like to ask: would you like to keep working on it from within our official repos?

**Comment by fefeh1** [comment]
Sure, I love the application and am glad I was able to do this.  :)
